### ISSUE TITLE
Don't replace content on data-prop

### ISSUE THREAD

**Issue by iamvery** [iamvery/ratchet#28]
There are certain cases where it is not desirable to replace the content of an element with `data-prop`.

For e.g., given a template such as:

``` html
<div data-scope="comment">
  <p data-prop="body"></p>
  <a data-prop="delete">Delete</a>
</div>
```

It is desirable to bind only attributes to the "delete" property, and leave the content unchanged, resulting in the following view:

``` html
<div data-scope="comment">
  <p data-prop="body">I have thoughts and feelings</p>
  <a href="/comments/1" method="delete" data-prop="delete">Delete</a>
</div>
```

---
## Proposal

Just as attributes are bound when data property is of the form `{content, attrs}`, this case would also be dictated by the type of data that is given.

So with the above template and the following data:

``` elixir
data = %{
  comment: %{
    body: "I have thoughts and feelings",
    delete: [href: "/comments/1", method: "delete"],
  }
}
```

Only attributes would be written for the "delete" data property.

Does this work?

**Comment by iamvery** [comment]
Worth noting that with such a change, the values of data property would come in four forms:
1. binary, e.g. `"foo"` - updates content only
2. tuple, e.g. `{"foo", href: "..."}` - updates content and attributes
3. list, e.g. `["foo", {"bar", class: "btn"}]` - duplicates data-prop and updates each accordingly
4. keyword list, e.g. `[href: "...", rel: "nofollow"]` - updates attributes only

**Comment by iamvery** [comment]
It sort of feels like # 4 complicates things a bit. Perhaps we should consider using a Map here instead. Might make the implementation simpler with a guard.

**Comment by dgmcguire** [comment]
:+1: on using a map.  I've already considered that there might be some refactoring in the transformer that could make the code more terse if we used a map, but I'm not sure that refactor was really a good decision now, but never-the-less it is another example of where we would have achieved more flexibility if we used a map over a list.

**Comment by iamvery** [comment]
This would probably also help support #25

**Comment by iamvery** [comment]
This was done in #40
